### PR TITLE
Chainlink tutorial 1

### PR DESCRIPTION
**Pull request by dvinubius**
Updates, cleanup, fixed some links

### CODE REVIEW

**Comment by dvinubius** [comment]
@codenamejason Tutorials 2 and 3 are also ready
Can we create branches for them, so I can open PRs?
https://github.com/dvinubius/scaffold-eth-examples/tree/chainlink-tutorial-2
https://github.com/dvinubius/scaffold-eth-examples/tree/chainlink-tutorial-3

**Comment by codenamejason** [comment]
I will do this morning

**Review by codenamejason — APPROVED** [review]
Dope 🔥

**Comment by codenamejason** [comment]
Screen Shot 2021-12-10 at 10 42 06 AM

**Comment by codenamejason** [comment]
@dvinubius ^^^^^ did the branches for your prs 🔥

**Comment by dvinubius** [comment]
@codenamejason ser, just realized that i had mistaken you for austin. i'm new to the community
sorry about that :) 
i've made PR's for the tutorials 2 and 3

**Pull request merged**
